### PR TITLE
Initial setup of the repo to make it easy for students to clone the project in VS2019

### PR DESCRIPTION
**Pull request by mikemag**
Alright, here's a pull request to get the repo close to what I think we need to make it easy for the students to get started. I have some notes from you in email about your first try doing this. I'll address them in subsequent comments here, so we can discuss. Don't accept this pull request until we work it out, I think there's one update I should make!

### CODE REVIEW

**Comment by mikemag** [comment]
Okay, I have an email from you about some issues you ran into trying to clone and use this in VS2019. 

I don’t know if some of the issues you ran into were due to a fresh VS2019 install, or something else. Let me try to take them one at a time.

1)	Yes, you have to use the right URL for the clone. In this case, it’s https://github.com/mikemag/WilliamsGameEngineVS2019.git, which can be found from the green Clone or Download button. 
2)	On what happens next, for me I previously had Solution Explorer open, so it was already available for me. I tried closing it, and all of my little windows in VS, and exited, then did it all again, but Solution Explorer opened for me. Strange. 
3)	Okay, I think I see where things have gone wrong. With only Team Explorer open, I think it showed you MyGame.sln near the bottom of the view. Double clicking on that does not do at all what I expect.
a.	It ends up in a rather strange state, showing the solution not as a runnable thing, but as just a collection of files to edit. That’s likely whey you had to add a button.

So, I think the instructions would be as follows:
1)	Launch VS2019
2)	Click “Clone or check out code”
3)	Paste in https://github.com/mikemag/WilliamsGameEngineVS2019.git and click Clone
4)	After it finishes cloning, open Solution Explorer with View -> Solution Explorer
5)	Open Base Project -> MyGame and double-click MyGame.sln
6)	This should open the solution and the tool bar should now contain a run button with “Debug, Win32, Local Windows Debugger”.
7)	Press play and see it compile and run, showing a blank window ready for the tutorial to start.

Alternative would be:
1)	Go to https://github.com/mikemag/WilliamsGameEngineVS2019 
2)	Click on the green “Clone or Download”
3)	Click on “Download Zip” to download a copy of the repository
4)	Unzip the files to wherever you’d like.
5)	Navigate to Base Project -> MyGame within the new directory and double-click MyGame.sln.
6)	This should open the solution and the tool bar should now contain a run button with “Debug, Win32, Local Windows Debugger”.
7)	Press play and see it compile and run, showing a blank window ready for the tutorial to start.

**Comment by mikemag** [comment]
Now, you also had an issue with the first run:

"Clicked on the play button.  Build errors.  Windows SDK version 10.0.17134.0 was not found.  Changed the property (Configuration Properties -> General -> Windows SDK Version) to 10.0 (latest installed version) instead of the specific version found.  That did the trick."

I think I can fix hat with a change to the solution file. Let me do that and update this PR.

**Comment by MichaelTMiyoshi** [comment]
An interesting thing that you note is that when you double-clicked the .sln file, you had a strange error.  When I did that (the second time), I had no problems.  Just that the solution explorer did not show up.

**Comment by mikemag** [comment]
I have updated the PR to include switching the default Windows SDK version to "10.0, latest"

**Comment by MichaelTMiyoshi** [comment]
It is funny.  3a was what happened to me the first time.

**Comment by mikemag** [comment]
I recommend that you delete your direction where you cloned my repo and go through the steps I outlined above. If it works now, then I suggest we add those steps to the main README.md, so students see the instructions when they go to the repo.

What do you think?

**Comment by MichaelTMiyoshi** [comment]
I see a new potential problem.  Probably just in the instructions.

I deleted the old project and created a new clone (from Visual Studio).  This time, I ended up with the Team Explorer tab "behind" the solution explorer.  This is where I think my confusion came in the first time.  So we will need to say something about that.

SolutionTeamExplorer

They need to make sure to click the Team Explorer tab.  Then, double-clicking on the .sln file opens the project.  No files are shown, but they can see what they usually see in the solution explorer.

image

I did not need to do anything to the solution.  Just hit the play button.  (Which does not show the configuration or anything like it usually does.)

**Comment by mikemag** [comment]
Ah, I think it's actually _good_ that Solution Explorer pops up. I found it more confusing to double click the solution from Team Explorer. What do you think?

**Comment by mikemag** [comment]
After I clone the project, if I go back to the Team explorer this is my view:

Screen Shot 2020-04-20 at 3 29 07 PM

I then have to double click the last project I cloned to see the .sln there, then double clicking that leads me here:

Screen Shot 2020-04-20 at 3 30 01 PM

With the solution view in a rather strange state, with no run buttons.

But if I follow the instructions I have above and open the .sln from Solution Explorer, everything is groovy, as if I'd opened it from the filesystem.

**Comment by MichaelTMiyoshi** [comment]
The only problem with solution explorer popping up is that the students might be inclined to try to burrow down there to find the solution.  That is what I did the first time.  And that did not work.  It did work when I double-clicked in the Team Explorer window.

Here is the thing though.  It does not matter how perfect the instructions are, not everybody will follow them.  You and I both know that some people read and follow directions well.  Others just skim.  And still others do what they think that they read (or skimmed).  So there is no foolproof instruction set.  People will still get it wrong.  (I actually did what I thought the directions said, but I think I missed a step in there.)

I do think it weird that the run button does not pop up, but I wonder if that is a VS 2019 issue.  It did not show up for my first console project either.

**Comment by mikemag** [comment]
> Here is the thing though. It does not matter how perfect the instructions are, not everybody will follow them.

You're so very right!! 

Alright then, wanna try it as is then? I added instructions to the readme. with a commit above. If you like it, go ahead and accept the pull request.

**Comment by mikemag** [comment]
Oh, one thing I did notice is that if I exit VS, then re-launch and select the MyGame solution at the top of the recent projects list, it comes up perfectly no matter what state I was in before :)

**Comment by MichaelTMiyoshi** [comment]
So is this the point where we say it is good and I merge the pull request?  The thing that I do not quite get is that the Merge pull request button seems to me to be merge with your own master, but you have been working on your master.  I guess I need to understand the vocabulary.

**Comment by mikemag** [comment]
Yes, now is the time to accept and merge. I had poor form: I worked out of my master branch, which makes it confusing. I should have worked in a branch. I'll do better next time!

**Comment by MichaelTMiyoshi** [comment]
No.  I just looked up at the top of the pull request and read there.  That makes things more understandable.  So merge commit, squash and merge, or rebase and merge.  I read the differences of the bottom two, but I am not sure which is the one to use in this case.

**Comment by MichaelTMiyoshi** [comment]
Oops.  Should be a question mark about the type of merge.

**Comment by mikemag** [comment]
I usually do "Merge Commit"

**Comment by MichaelTMiyoshi** [comment]
image

That was my question.

**Comment by MichaelTMiyoshi** [comment]
Okey dokey.  Merge commit.

**Comment by MichaelTMiyoshi** [comment]
After I do the merge pull request, what do I do then?  Close and Comment?  And what happens to the repo?  I thought it would be magically like yours now.

**Comment by mikemag** [comment]
When you select "Create a merge commit" you then have to take a couple of steps to commit it. Basically, it makes a change on your behalf which includes all of my changes, and now you need to commit that.

See https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-a-pull-request

**Comment by mikemag** [comment]
Excellent!!! We're off to the races :)

**Comment by MichaelTMiyoshi** [comment]
Interesting that the number 5 section never happened.  I confirmed the merge though.  Seems easy enough.  Thanks for the lesson.  Quite an educational process.  Like I said, I need to get used to thinking of everything the students are doing as a collaboration.  Either with me (and you) or with other students or a combination thereof.  Then, this makes even more sense.

**Pull request merged**
